all:
	(cd rest-core; make $(MFLAGS) all)
	(cd rest-textui-manager; make $(MFLAGS) all)
	(cd rest-textui-outlet; make $(MFLAGS) all)
	#(cd rest-tests; make $(MFLAGS) all)

clean:
	(cd rest-core; make $(MFLAGS) clean)
	(cd rest-textui-manager; make $(MFLAGS) clean)
	(cd rest-textui-outlet; make $(MFLAGS) clean)
	#(cd rest-tests; make $(MFLAGS) clean)

install:
	(cd rest-core; make $(MFLAGS) install)
	(cd rest-textui-manager; make $(MFLAGS) install)
	(cd rest-textui-outlet; make $(MFLAGS) install)
	#(cd rest-tests; make $(MFLAGS) install)
